const ADD_TASK = 'ADD_TASK';
const EDIT_TASK = 'EDIT_TASK';
const TOGGLE_TASK = 'COMPLETE_TASK';
const SAVE_TASK = 'SAVE_TASK';
const SELECT_TASK = 'SELECT_TASK';

export default {
  ADD_TASK,
  EDIT_TASK,
  TOGGLE_TASK,
  SAVE_TASK,
  SELECT_TASK
}
